### ISSUE TITLE
not compatible with magento 2.4.4

### ISSUE THREAD

**Issue by PascalBrouwers** [justbetter/magento2-sentry#105]
not compatible with magento 2.4.4

```
PHP Fatal error:  Declaration of JustBetter\Sentry\Plugin\MonologPlugin::addRecord($level, $message, array $context = Array) must be compatible with Monolog\Logger::addRecord(int $level, string $message, array $context = Array, ?Monolog\DateTimeImmutable $datetime = NULL): bool in /vendor/justbetter/magento2-sentry/Plugin/MonologPlugin.php on line 54
```

**Comment by indykoning** [comment]
To make this compatible with 2.4.4 you have to update to version 3.1.0+ 🙂 
https://github.com/justbetter/magento2-sentry/commit/8326975e7b5f8d4a6203b8e994d93a28331f0fe3

**Comment by peterjaap** [comment]
@indykoning are you sure?

That commit only adds `$datetime` as an argument to the `parent::addRecord` but in 2.4.4 the complete `addRecord` method has been removed; https://github.com/magento/magento2/blob/2.4.4/lib/internal/Magento/Framework/Logger/Monolog.php

In 2.4.3 it was still there; https://github.com/magento/magento2/blob/2.4.3/lib/internal/Magento/Framework/Logger/Monolog.php#L34

**Comment by peterjaap** [comment]
Right, i see now. Magento previously had that `addRecord` method overridden in their own lib. That wasn't needed anymore because of reasons (?) and now it gave an error because of `datetime` missing. So the easy fix was to remove the whole override, dus making `parent::addRecord` call to the original addRecord method in de Monolog package; https://github.com/Seldaek/monolog/blob/main/src/Monolog/Logger.php#L314

**Comment by emreakay** [comment]
any solution?
