### ISSUE TITLE
Allow usage of Debug IDs for uploading source maps

### ISSUE THREAD

**Issue by norgeindian** [justbetter/magento2-sentry#124]
**Do you want to request a *feature* or report a *bug*?**
Feature

**Feature: What is your use case for such a feature?**
We would like to upload source maps to sentry, so that we understand the origin of JS issues.
According to Sentry, this is either possible via Debug IDs (which is the recommended way) or via releases.
When I try to set up the upload via Debug IDs, I get the following error message:

![Screenshot from 2024-01-03 10-48-05](https://github.com/justbetter/magento2-sentry/assets/11156287/719b0d98-e1cf-4c8c-8356-a4e0e8c35244)

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**
I would propose to update `\JustBetter\Sentry\Block\SentryScript` to use the newest version. 

**What is the version of Magento and of Sentry extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento 2.4.6-p3 and module version 3.5.1

How do others currently solve that issue? So, how do you upload your source maps? Is there maybe also a way, using releases?

**Comment by indykoning** [comment]
In order to test the newer/older versions out we have the https://github.com/justbetter/magento2-sentry#:~:text=in%20develop%20mode.-,js_sdk_version,-%3A%20if%20this%20option option.
So you can override the SDK version of sentry being used.

You could try that out, and if it works we would really appreciate a PR with the newer version that works/has fixes for the newer version 😄

**Comment by norgeindian** [comment]
@indykoning , thanks for the information. To be honest, we then decided to also send the release data and since then it works as well. But if we ever come into a similar situation again, I will be happy to try it the suggested way.
