### ISSUE TITLE
Setup by CLI

### ISSUE THREAD

**Issue by mortenbirkelund** [justbetter/magento2-sentry#50]
Hi

After updating to the latest version of this module, it seems it is no longer possible to setup using CLI. 

```
php ~/public_html/bin/magento module:enable JustBetter_Sentry
php ~/public_html/bin/magento config:set sentry/general/enabled 1
php ~/public_html/bin/magento config:set sentry/general/dsn https://mydns@sentry.io/1234567
php ~/public_html/bin/magento config:set sentry/general/environment under-development
```

This was working in previous a previous version but now I get an error saying that the path doesnt exist. 

Have the configuration path been changed? I understand that the settings have been moved, but even with `--lock-env` it still doesnt work

I am sure it is just me who missed something obvious, but not sure what it is :)

**Comment by indykoning** [comment]
This has indeed changed.
https://github.com/justbetter/magento2-sentry/blob/master/etc/adminhtml/system.xml
Here you can find the paths and configuration that is available, in short:
`sentry/general/deployment_config_info`
`sentry/general/enable_script_tag `
`sentry/general/script_tag_placement`

https://github.com/justbetter/magento2-sentry/commit/8a5598e81973cc426c07f52d607689974c6aa572
is the commit, it has been changed since V2.0.0

**Comment by mortenbirkelund** [comment]
So it is no longer possible to to the setup of dsn and environment from commandline? Only by editing the env.php file manually?

**Comment by indykoning** [comment]
Yes, that is correct.

**Comment by mortenbirkelund** [comment]
@indykoning Thank you for answering.
