### ISSUE TITLE
ErrorException in Version 2.5.0

### ISSUE THREAD

**Issue by simonmaass** [justbetter/magento2-sentry#68]
ErrorException
Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead

![Unbenannt](https://user-images.githubusercontent.com/32599710/104719545-ea89a980-572c-11eb-8596-cf2ca9d99149.png)

**Comment by matthiashamacher** [comment]
@simonmaass 
Sorry about that. During testing I didn't got any errors. 
I will have a look at it during the weekend.

**Comment by indykoning** [comment]
Hi Simon,
this has now been fixed in 2.5.2 which should be available now 🎉 

If you have custom code calling the [send function of the sentrylog model](https://github.com/justbetter/magento2-sentry/blob/fe45d45b1460b88a2d00c666e2177b1990f5360b/Model/SentryLog.php#L63) check that `monolog` is not an argument in those functions anymore.

Let us know if you run into any problems with it 🙂

**Comment by simonmaass** [comment]
works - thank you!
